### ISSUE TITLE
Image Shortcut Causes Error

### ISSUE THREAD

**Issue by staticextasy** [andersevenrud/OS.js-v2#113]
![image](https://cloud.githubusercontent.com/assets/6365639/7752383/22b60732-ffad-11e4-894f-c38f3d48f221.png)

Double-Clicking on image-shortcut icon from desktop causes Error Dialog. I can open the image from the File Manager, it lets me select an application to run the image in. 

    Error: This function excepts a OSjs.VFS.File object
    at _Handler.getApplicationNameByFile (http://localhost:8000/osjs.js:4377:13)
    at Object.doLaunchFile [as open] (http://localhost:8000/osjs.js:1431:13)
    at opts.onActivate (http://localhost:8000/packages/default/CoreWM/combined.js:315:15)
    at _DataView._onActivate (http://localhost:8000/osjs.js:10848:23)
    at HTMLLIElement.<anonymous> (http://localhost:8000/osjs.js:11315:16)

**Comment by andersevenrud** [comment]
Thanks, mate :) Will fix this

**Comment by staticextasy** [comment]
Seems this bug is related to any custom created shortcuts, I just tried a shortcut to a text document and I get the same result.


    Error: This function excepts a OSjs.VFS.File object
    at _Handler.getApplicationNameByFile (http://localhost:8000/osjs.js:4377:13)
    at Object.doLaunchFile [as open] (http://localhost:8000/osjs.js:1431:13)
    at opts.onActivate (http://localhost:8000/packages/default/CoreWM/combined.js:315:15)
    at _DataView._onActivate (http://localhost:8000/osjs.js:10848:23)
    at HTMLLIElement.<anonymous> (http://localhost:8000/osjs.js:11315:16)

**Comment by andersevenrud** [comment]
It is fixed now. It was a problem with desktop shortcuts in general :)

**Comment by andersevenrud** [comment]
The best way to update codebase for changes like this is like this btw:

```
# Get changes
git pull

# If using "dist". Build core and package changes only
grunt core packages
```
