### ISSUE TITLE
Rename File Error

### ISSUE THREAD

**Issue by staticextasy** [andersevenrud/OS.js-v2#114]
![image](https://cloud.githubusercontent.com/assets/6365639/7753648/d4285fae-ffb4-11e4-82a0-f91c666b6c6e.png)

Error when attempting to rename file in File Manager. I'm guessing it creates a phantom file there as well, if i close out of the error dialog and try to open the file in Preview I get this image:

![image](https://cloud.githubusercontent.com/assets/6365639/7753692/19c9bd46-ffb5-11e4-92aa-bbd18dfc464d.png)

    TypeError: Cannot read property 'Public' of undefined
    at http://localhost:8000/osjs.js:5016:26
    at _finished (http://localhost:8000/osjs.js:4948:9)
    at http://localhost:8000/osjs.js:4973:13
    at Object.<anonymous> (http://localhost:8000/osjs.js:4636:9)
    at Object.<anonymous> (http://localhost:8000/osjs.js:1384:13)
    at Object.data.onsuccess (http://localhost:8000/osjs.js:7953:19)
    at XMLHttpRequest.onReadyStateChange (http://localhost:8000/osjs.js:727:16)

**Comment by andersevenrud** [comment]
Thanks! This seems to be a Windows issue. Guessing it has something to do with path resolving.

Will fix :)

**Comment by andersevenrud** [comment]
Scratch comment below. It is actually a spelling error. Ooopsie! :)

**Comment by andersevenrud** [comment]
Fixed now.
