### ISSUE TITLE
Error when opening app menu on chrome for android

### ISSUE THREAD

**Issue by xDarkShadowKnightx** [andersevenrud/OS.js-v2#156]
Here's the error that popped up:

TypeError: OSjs.Core.getHandler(...).getApplicationsMetadata is not a function
    at new ApplicationMenu (http://osjsv2.0o.no/packages/default/CoreWM/combined.js:1:2029)
    at Object.doShowMenu [as showMenu] (http://osjsv2.0o.no/packages/default/CoreWM/combined.js:1:3763)
    at http://osjsv2.0o.no/packages/default/CoreWM/combined.js:1:35213
    at http://osjsv2.0o.no/osjs.js:1:23793
    at HTMLLIElement.touchEnd (http://osjsv2.0o.no/osjs.js:1:23055)

**Comment by andersevenrud** [comment]
Should be fixed now (demo site is cached, so might have to refresh two times to make it update).
