### ISSUE TITLE
[Package Manager] Error on install package from store

### ISSUE THREAD

**Issue by 1j01** [andersevenrud/OS.js-v2#172]
Trying to install "Test" in Settings > Packages > App Store

```
Error: File expects at least one argument
    at new FileMetadata (http://osjsv2.0o.no/osjs.js:8733:13)
    at PackageManager.install (http://osjsv2.0o.no/osjs.js:4497:15)
    at http://osjsv2.0o.no/packages/default/Settings/combined.js:68:39
    at _finished (http://osjsv2.0o.no/osjs.js:8848:7)
    at Object.<anonymous> (http://osjsv2.0o.no/osjs.js:8580:9)
    at Object.<anonymous> (http://osjsv2.0o.no/osjs.js:1567:13)
    at Object.data.onsuccess (http://osjsv2.0o.no/osjs.js:8292:19)
    at XMLHttpRequest.onReadyStateChange (http://osjsv2.0o.no/osjs.js:1222:16)
```

I'm guessing maybe this isn't "supposed to work" yet?

**Comment by andersevenrud** [comment]
Ah, yes. The "App Store" is not working on the public demo :)

**Comment by 1j01** [comment]
I got the same error after installing OS.js locally

**Comment by andersevenrud** [comment]
I see that too! Thanks :)

**Comment by andersevenrud** [comment]
The App Store is a work in progress btw, and I think the test application that is there is outdated. But at least this spesific error was fixed
