### ISSUE TITLE
Saved writer document can't be opened.

### ISSUE THREAD

**Issue by opalenet-marcandre** [andersevenrud/OS.js-v2#175]
This is the error I get:

```
Error: Cannot doLaunchFile() without a mime type
    at Object.doLaunchFile [as open] (http://v2b.nook.ink/client/javascript/api.js:339:32)
    at http://v2b.nook.ink/packages/default/FileManager/main.js:240:11
    at Array.forEach (native)
    at ApplicationFileManagerWindow.checkActivation (http://v2b.nook.ink/packages/default/FileManager/main.js:234:19)
    at UIElement.<anonymous> (http://v2b.nook.ink/packages/default/FileManager/main.js:158:14)
    at HTMLElement.cbNormal (http://v2b.nook.ink/client/javascript/utils/dom.js:590:18)
    at UIElement.<anonymous> (http://v2b.nook.ink/client/javascript/gui/fileview.js:54:10)
    at HTMLElement.cbNormal (http://v2b.nook.ink/client/javascript/utils/dom.js:590:18)
    at HTMLElement.activate (http://v2b.nook.ink/client/javascript/gui/_dataview.js:358:12)
    at HTMLElement.cbNormal (http://v2b.nook.ink/client/javascript/utils/dom.js:590:18)
```

**Comment by andersevenrud** [comment]
Is the file saved as `.odoc` ?

**Comment by andersevenrud** [comment]
I cannot replicate this error on my local machine. You're opening a file from File Manager, right ?

If you give me a login to your site maybe I can help debugging the problem.

**Comment by opalenet-marcandre** [comment]
it is saved as .odoc (I also tried changing it to .html, but it didn't help).
http://v2b.nook.ink/
u:drmab / p:mab

**Comment by andersevenrud** [comment]
Are you running PHP or Node server ? It seems that it fails to read MIME of files.

![Screenshot](http://i.imgur.com/QwEEqt6.png)

**Comment by opalenet-marcandre** [comment]
PHP. I tested with a jpeg, same problem. It's probably in my server config.

**Comment by andersevenrud** [comment]
It seems this is my fault. I forgot to make an update... please stand by!

**Comment by andersevenrud** [comment]
It seems that you may be missing a php module that makes the function `finfo_open` available. And in that case MIME reading seems to be failing.

Please update your source-code and try again with the latest update :)

**Comment by opalenet-marcandre** [comment]
Fixed it; my PHP configuration was missing the file type extension.

**Comment by andersevenrud** [comment]
Great! :)

I'm going to make a `grunt check` task that looks up the system configuration to and warn the user if anything is missing or possibly wrong.
