### ISSUE TITLE
Boh

### ISSUE THREAD

**Issue by kopiro** [andersevenrud/OS.js-v2#176]
An error occured while trying to launch: ApplicationChat

> Application 'ApplicationChat' init() failed: TypeError: Cannot read property 'appendChild' of undefined

```
TypeError: Cannot read property 'appendChild' of undefined
    at notification.wm.createNotificationIcon.onCreated (http://osjsv2.0o.no/packages/extras/Chat/combined.js:6411:22)
    at new NotificationAreaItem (http://osjsv2.0o.no/packages/default/CoreWM/combined.js:1615:20)
    at PanelItemNotificationArea.createNotification (http://osjsv2.0o.no/packages/default/CoreWM/combined.js:1668:20)
    at CoreWM.createNotificationIcon (http://osjsv2.0o.no/packages/default/CoreWM/combined.js:2898:24)
    at ApplicationChat.init (http://osjsv2.0o.no/packages/extras/Chat/combined.js:6405:30)
    at _callback (http://osjsv2.0o.no/osjs.js:1782:11)
    at http://osjsv2.0o.no/osjs.js:1826:11
```

**Comment by andersevenrud** [comment]
Thanks for letting me know :)

This was actually fixed in a previous commit, but it seems I have forgotten to update the demo site! I will run an update this weekend as I am planning to deploy some other stuff as well

**Comment by andersevenrud** [comment]
Ref: https://github.com/andersevenrud/OS.js-v2-extras/commit/1ff28ae8ee82541b241ab39f28622ef7ced7bc0c

**Comment by andersevenrud** [comment]
This issue should be fixed now.  I just applied an update :)
