### ISSUE TITLE
Trying to create a file in editor

### ISSUE THREAD

**Issue by MarkWalls** [andersevenrud/OS.js-v2#180]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'match' of null
    at $detectNewLine (http://osjsv2.0o.no/packages/extras/AceEditor/combined.js:6225:25)
    at insert (http://osjsv2.0o.no/packages/extras/AceEditor/combined.js:6297:18)
    at setValue (http://osjsv2.0o.no/packages/extras/AceEditor/combined.js:6205:14)
    at setValue (http://osjsv2.0o.no/packages/extras/AceEditor/combined.js:11536:26)
    at ApplicationAceEditorWindow.showFile (http://osjsv2.0o.no/packages/extras/AceEditor/combined.js:18608:17)
    at http://osjsv2.0o.no/osjs.js:11788:13
    at DefaultApplicationWindow.checkHasChanged (http://osjsv2.0o.no/osjs.js:11877:5)
    at DefaultApplication.newDialog (http://osjsv2.0o.no/osjs.js:11785:9)
    at Object.menuMap.MenuNew (http://osjsv2.0o.no/osjs.js:11820:36)
    at UIElement.<anonymous> (http://osjsv2.0o.no/osjs.js:11827:59)
```

**Comment by andersevenrud** [comment]
Thanks! This should be fixed in https://github.com/andersevenrud/OS.js-v2-extras/commit/d0a34d0e4e7dbd7b7054e7e9dd776e7320b11a39

I will update the demo server today at some point

**Comment by andersevenrud** [comment]
@MarkWalls I have updated the demo server, so it should work now (allthough you might have to clear your browser cache for it to refresh code properly... it happens sometimes)
