### ISSUE TITLE
I try to open with Chrome

### ISSUE THREAD

**Issue by gelopfalcon** [andersevenrud/OS.js-v2#183]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: this.get(...).querySelectorAll is not a function
    at Object.t.location.href.match.t.top.t.self.o.fn.find (<anonymous>:1:1813)
    at HTMLDocument.<anonymous> (<anonymous>:1:6020)
    at HTMLDocument.<anonymous> (<anonymous>:1:503)
    at update (http://osjsv2.0o.no/packages/default/CoreWM/combined.js:1485:15)
    at http://osjsv2.0o.no/packages/default/CoreWM/combined.js:1493:9
```

**Comment by andersevenrud** [comment]
I just updated the OS.js demo server. Could you please try again and see if you still get this ? (You should clear browser cache first)

**Comment by gelopfalcon** [comment]
The bug was fixed. Thanks.

**Comment by andersevenrud** [comment]
Thank you for reporting! :)
