### ISSUE TITLE
Clicked on start menu

### ISSUE THREAD

**Issue by wporquet** [andersevenrud/OS.js-v2#198]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: DialogRef is not a function
    at PanelItem.openSettings (http://osjsv2.0o.no/packages/default/CoreWM/combined.js:1114:28)
    at HTMLElement.API.createMenu.onClick (http://osjsv2.0o.no/packages/default/CoreWM/combined.js:1086:18)
    at HTMLElement.<anonymous> (http://osjsv2.0o.no/osjs.js:6091:26)
    at HTMLElement.cbTouch (http://osjsv2.0o.no/osjs.js:1081:18)
```

**Comment by andersevenrud** [comment]
You right-clicked the "start menu" or just pressed it normally ?

**Comment by andersevenrud** [comment]
Oh, you're using a touch-screen maybe ? I will make a note of it in #112

I have at least added a prevention for this error. Thanks for reporting! :)
