### ISSUE TITLE
cannot save text file

### ISSUE THREAD

**Issue by mgild** [andersevenrud/OS.js-v2#199]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'selected' of undefined
    at http://osjsv2.0o.no/osjs.js:8216:22
    at Object.<anonymous> (http://osjsv2.0o.no/osjs.js:9023:9)
    at Object.<anonymous> (http://osjsv2.0o.no/osjs.js:1614:13)
    at Object.data.onsuccess (http://osjsv2.0o.no/osjs.js:8712:19)
    at XMLHttpRequest.onReadyStateChange (http://osjsv2.0o.no/osjs.js:1140:16)
```

**Comment by andersevenrud** [comment]
Thanks! This should be fixed now :)
