### ISSUE TITLE
I created a file using the painting app, it crashed after I saved with this message

### ISSUE THREAD

**Issue by tswt** [andersevenrud/OS.js-v2#201]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'find' of null
    at DefaultApplicationWindow.updateFile (http://osjsv2.0o.no/osjs.js:12058:17)
    at http://osjsv2.0o.no/osjs.js:11910:11
    at _finished (http://osjsv2.0o.no/osjs.js:9298:7)
    at Object.<anonymous> (http://osjsv2.0o.no/osjs.js:9023:9)
    at Object.<anonymous> (http://osjsv2.0o.no/osjs.js:1614:13)
    at Object.data.onsuccess (http://osjsv2.0o.no/osjs.js:8712:19)
    at XMLHttpRequest.onReadyStateChange (http://osjsv2.0o.no/osjs.js:1140:16)
```

**Comment by andersevenrud** [comment]
Thanks for reporting! :)

I am not able to replicate this bug. You just:

- Opened "Draw"
- Made something
- Used "Save" from the menu
- Wrote a filename and confirmed

and then error showed up ?

**Comment by andersevenrud** [comment]
I'm pretty sure this got fixed in the recent update -- if not I will re-open.
