### ISSUE TITLE
Unexpected error on browsing home directory

### ISSUE THREAD

**Issue by AhmedAlSammany** [andersevenrud/OS.js-v2#220]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'find' of null
    at ApplicationFileManagerWindow.checkSelection (http://osjsv2.0o.no/packages/default/FileManager/combined.js:212:33)
    at Object.view._call.done (http://osjsv2.0o.no/packages/default/FileManager/combined.js:406:14)
    at http://osjsv2.0o.no/osjs.js:7042:18
    at row.value (http://osjsv2.0o.no/osjs.js:6896:7)
    at http://osjsv2.0o.no/osjs.js:6853:7
    at http://osjsv2.0o.no/osjs.js:9286:7
    at http://osjsv2.0o.no/osjs.js:9745:7
    at Object.<anonymous> (http://osjsv2.0o.no/osjs.js:9023:9)
    at Object.<anonymous> (http://osjsv2.0o.no/osjs.js:1614:13)
    at Object.data.onsuccess (http://osjsv2.0o.no/osjs.js:8712:19)
```

**Comment by andersevenrud** [comment]
This update should take care of that problem.

Thanks for reporting! :)
