### ISSUE TITLE
Click [OK] button on file information

### ISSUE THREAD

**Issue by UziTech** [andersevenrud/OS.js-v2#233]
1. open file manager
2. right click file
3. click information
4. click OK

```
TypeError: callback.apply is not a function
    at DialogWindow.closeCallback (http://localhost:8888/client/javascript/dialog.js:81:16)
    at DialogWindow.onClose (http://localhost:8888/client/javascript/dialog.js:124:10)
    at UIElement.<anonymous> (http://localhost:8888/client/javascript/dialog.js:113:16)
    at HTMLButtonElement.cbNormal (http://localhost:8888/client/javascript/utils/dom.js:607:18)
```

**Comment by andersevenrud** [comment]
Much appreciated! :)
