### ISSUE TITLE
I have tried to open dropbox.js

### ISSUE THREAD

**Issue by shohrukh92** [andersevenrud/OS.js-v2#239]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
Error: Cannot doLaunchFile() without a mime type
    at Object.doLaunchFile [as open] (http://osjsv2.0o.no/osjs.js:1622:32)
    at http://osjsv2.0o.no/packages/default/FileManager/combined.js:651:13
    at Array.forEach (native)
    at ApplicationFileManager.open (http://osjsv2.0o.no/packages/default/FileManager/combined.js:649:11)
    at Object.menuMap.MenuOpen (http://osjsv2.0o.no/packages/default/FileManager/combined.js:112:44)
    at UIElement.menuEvent (http://osjsv2.0o.no/packages/default/FileManager/combined.js:131:30)
    at HTMLLabelElement.cbNormal (http://osjsv2.0o.no/osjs.js:1078:18)
    at HTMLElement.<anonymous> (http://osjsv2.0o.no/osjs.js:5938:18)
    at HTMLElement.cbNormal (http://osjsv2.0o.no/osjs.js:1078:18)
```

**Comment by andersevenrud** [comment]
This file is broken on the demo server -- will fix
