### ISSUE TITLE
File manager err

### ISSUE THREAD

**Issue by zeyd17** [andersevenrud/OS.js-v2#243]
TypeError: Cannot read property 'find' of null
    at ApplicationFileManagerWindow.updateSideView (http://osjsv2.0o.no/packages/default/FileManager/combined.js:286:28)
    at Object.view._call.done (http://osjsv2.0o.no/packages/default/FileManager/combined.js:412:14)
    at http://osjsv2.0o.no/osjs.js:7051:18
    at http://osjsv2.0o.no/osjs.js:6905:7
    at http://osjsv2.0o.no/osjs.js:6862:7
    at http://osjsv2.0o.no/osjs.js:9305:7
    at http://osjsv2.0o.no/osjs.js:9764:7
    at Object.<anonymous> (http://osjsv2.0o.no/osjs.js:9042:9)
    at Object.<anonymous> (http://osjsv2.0o.no/osjs.js:1613:11)
    at Object.data.onsuccess (http://osjsv2.0o.no/osjs.js:8731:19)
```

**Comment by andersevenrud** [comment]
Thanks for reporting!
