### ISSUE TITLE
Баг

### ISSUE THREAD

**Issue by Jaguarstaff** [andersevenrud/OS.js-v2#244]
Проихошла непредвиденная ошибка, возможно баг.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'find' of null
    at ApplicationCalculatorWindow._focus (http://osjsv2.0o.no/packages/default/Calculator/combined.js:269:31)
    at onMouseDown (http://osjsv2.0o.no/osjs.js:3973:11)
    at HTMLElement.<anonymous> (http://osjsv2.0o.no/osjs.js:4140:9)
    at HTMLElement.cbNormal (http://osjsv2.0o.no/osjs.js:1079:18)
```

**Comment by andersevenrud** [comment]
Thanks for reporting, fixing it as we speak! :)
