### ISSUE TITLE
An unexpected error occured, IDE + PAM authentication.

### ISSUE THREAD

**Issue by rodrigoselau** [andersevenrud/OS.js-v2#245]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'children' of undefined
    at traverse (http://192.168.10.35:8000/packages/default/Ide/window-properties.js:252:16)
    at ApplicationIDEPropertiesWindow.renderTree (http://192.168.10.35:8000/packages/default/Ide/window-properties.js:284:5)
    at ApplicationIDEPropertiesWindow.load (http://192.168.10.35:8000/packages/default/Ide/window-properties.js:136:10)
    at ApplicationIDE.windowAction (http://192.168.10.35:8000/packages/default/Ide/main.js:97:19)
    at http://192.168.10.35:8000/packages/default/Ide/main.js:117:14
    at http://192.168.10.35:8000/packages/default/Ide/init.js:397:9
    at UIScheme.loadString (http://192.168.10.35:8000/client/javascript/gui/_scheme.js:197:5)
    at VFS.read.type (http://192.168.10.35:8000/packages/default/Ide/init.js:385:19)
    at _finished (http://192.168.10.35:8000/client/javascript/vfs.js:808:9)
    at http://192.168.10.35:8000/client/javascript/vfs.js:831:9
```

![sem titulo](https://cloud.githubusercontent.com/assets/5107680/12102478/21ad359e-b322-11e5-92be-63f77634a591.png)

**Comment by andersevenrud** [comment]
The IDE is a work in progress and not anywhere near finsished

**Comment by andersevenrud** [comment]
#134
