### ISSUE TITLE
sha

### ISSUE THREAD

**Issue by lishuang0606** [andersevenrud/OS.js-v2#261]
发生未知异常, 也许是个BUG.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'find' of null
    at ApplicationWriterWindow.updateFile (http://osjsv2.0o.no/packages/default/Writer/combined.js:392:26)
    at http://osjsv2.0o.no/osjs.js:12020:11
    at _finished (http://osjsv2.0o.no/osjs.js:9396:7)
    at null.<anonymous> (http://osjsv2.0o.no/osjs.js:9117:9)
    at null.<anonymous> (http://osjsv2.0o.no/osjs.js:1614:11)
    at Object.data.onsuccess (http://osjsv2.0o.no/osjs.js:8799:21)
    at XMLHttpRequest.onReadyStateChange (http://osjsv2.0o.no/osjs.js:1141:16)
```

**Comment by andersevenrud** [comment]
This was already solved as part of another update. Demo server is just out of date :)
