### ISSUE TITLE
Error on uploading large files >40MB

### ISSUE THREAD

**Issue by angeloz** [andersevenrud/OS.js-v2#267]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'apply' of undefined
    at cb (http://lininoti.local/osjs.js:2143:15)
    at DialogWindow.closeCallback (http://lininoti.local/osjs.js:3913:16)
    at DialogWindow.onClose (http://lininoti.local/osjs.js:3948:10)
    at UIElement.<anonymous> (http://lininoti.local/osjs.js:3940:16)
    at HTMLButtonElement.cbNormal (http://lininoti.local/osjs.js:1079:18)
```

**Comment by andersevenrud** [comment]
You got the message "File exceeded: something" and then this error, right ?

**Comment by andersevenrud** [comment]
Thanks for reporting!

To increase the max upload size  do, ex:

```
# Set limit to ~200MB
grunt config:set:client.VFS.MaxUploadSize:209715200
grunt config

# Make sure to restart server
```

**Comment by angeloz** [comment]
Thank you Anders!
