### ISSUE TITLE
The error message window can't be closed

### ISSUE THREAD

**Issue by angeloz** [andersevenrud/OS.js-v2#268]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'apply' of undefined
    at cb (http://lininoti.local/osjs.js:2143:15)
    at DialogWindow.closeCallback (http://lininoti.local/osjs.js:3913:16)
    at DialogWindow.onClose (http://lininoti.local/osjs.js:3948:10)
    at DialogWindow._close (http://lininoti.local/osjs.js:3952:12)
    at Window._onWindowButtonClick (http://lininoti.local/osjs.js:3785:12)
    at HTMLElement.<anonymous> (http://lininoti.local/osjs.js:3048:16)
    at HTMLElement.cbNormal (http://lininoti.local/osjs.js:1079:18)
```

**Comment by andersevenrud** [comment]
Related to #267 :)
